[2024-06-25T11:29:53.867+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T11:29:53.884+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2024-06-25T11:29:53.684403+00:00 [queued]>
[2024-06-25T11:29:53.888+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2024-06-25T11:29:53.684403+00:00 [queued]>
[2024-06-25T11:29:53.889+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-25T11:29:53.894+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-06-25 11:29:53.684403+00:00
[2024-06-25T11:29:53.897+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'manual__2024-06-25T11:29:53.684403+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dag.py', '--cfg-path', '/tmp/tmp4oks44rw']
[2024-06-25T11:29:53.898+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask create_postgres_table
[2024-06-25T11:29:53.898+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=20215) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-25T11:29:53.898+0000] {standard_task_runner.py:63} INFO - Started process 20216 to run task
[2024-06-25T11:29:53.917+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2024-06-25T11:29:53.684403+00:00 [running]> on host 3b316f897547
[2024-06-25T11:29:53.983+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jack' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T11:29:53.684403+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-25T11:29:53.684403+00:00'
[2024-06-25T11:29:53.984+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T11:29:54.010+0000] {sql.py:276} INFO - Executing: 
            CREATE SCHEMA IF NOT EXISTS customer_schema;

            DROP TABLE IF EXISTS customer_schema.customer_table;

            CREATE TABLE customer_schema.customer_table (
                InvoiceNo TEXT,
                StockCode TEXT,
                "Description" TEXT,
                Quantity INT,
                InvoiceDate TIMESTAMP,
                UnitPrice FLOAT,
                CustomerID TEXT,
                Country TEXT
            );
             
[2024-06-25T11:29:54.016+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-25T11:29:54.021+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-25T11:30:02.031+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T11:30:02.034+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 175, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Temporary failure in name resolution

[2024-06-25T11:30:02.060+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, run_id=manual__2024-06-25T11:29:53.684403+00:00, execution_date=20240625T112953, start_date=20240625T112953, end_date=20240625T113002
[2024-06-25T11:30:02.072+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task create_postgres_table (could not translate host name "host.docker.local" to address: Temporary failure in name resolution
; 20216)
[2024-06-25T11:30:02.107+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-25T11:30:02.119+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-06-25T11:30:02.128+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T11:30:02.129+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
